name: CGM Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
    - name: Test with pytest
      run: |
        pip install pytest
        pytest ./tests