name: Publish to PyPi
on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types: [released]
jobs:
  publish: 
    name: publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
            python-version: 3.12.2
      - name: Build package
        run: |
          python -m pip install -U pip build
          python -m build
      - name : Publish cgm to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0